---
- name: add locales
  locale_gen:
    name: '{{ item }}'
    state: present
  with_items: '{{ locale_locales }}'
  notify: refresh locales | locale

- name: Install Language Packs | apt
  apt:
    state: latest
    pkg: "language-pack-{{ item }}"
  with_items:
    - "{{ locale_language_packs }}"
